(load "apply.scm")

(apply-closure '((((u v w)
		   (1 2 3))
		  ((x y z )
		   (4 5 6)))
		 (x y)
		 (cons z x)) '((a b c) (d e f)))
(meaning '(cons z x) '(((x y)
		       ((a b c)(d e f)))
		      ((u v w)
		       (1 2 3))
		      ((x y z)
		       (4 5 6))))

(meaning 'z '(((x y)
	       ((a b c)(d e f)))
	      ((u v w)
	       (1 2 3))
	      ((x y z)
	       (4 5 6))))

(apply-closure '((((u v w)
		  (1 2 3))
		 ((x y z)
		  (4 5 6)))
	       (x y)
	       (cons z x)) '((a b c) (d e f)))

(meaning '(lambda(x) (cons x y)) '(((y z) ((8) 9)))
		 )
